# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-21 14:39
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='answer_model',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('option', models.CharField(max_length=500)),
                ('vote', models.IntegerField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='history_model',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('taken', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='poll_model',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('poll_name', models.CharField(max_length=1000)),
                ('poll_status', models.CharField(max_length=1)),
                ('poll_start', models.DateField(null=True)),
                ('poll_end', models.DateField(null=True)),
                ('eligible', models.CharField(max_length=100, null=True)),
                ('vote', models.IntegerField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='question_model',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(max_length=2000)),
                ('poll_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_poll_core.poll_model')),
            ],
        ),
        migrations.AddField(
            model_name='history_model',
            name='poll',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_poll_core.poll_model'),
        ),
        migrations.AddField(
            model_name='history_model',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='answer_model',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_poll_core.question_model'),
        ),
    ]
