# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-29 12:52
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='answer_model',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('option', models.CharField(max_length=500)),
                ('vote', models.IntegerField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='history_model',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(max_length=100)),
                ('taken', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='poll_group_model',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('poll_group', models.CharField(max_length=80)),
            ],
        ),
        migrations.CreateModel(
            name='poll_model',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('poll_name', models.CharField(max_length=1000)),
                ('poll_start', models.DateField(db_index=True, null=True)),
                ('poll_end', models.DateField(db_index=True, null=True)),
                ('created_by', models.CharField(max_length=8)),
                ('total_vote', models.IntegerField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='question_model',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(max_length=2000)),
                ('poll_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_poll_core.poll_model')),
            ],
        ),
        migrations.AddField(
            model_name='poll_group_model',
            name='poll_name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_poll_core.poll_model'),
        ),
        migrations.AddField(
            model_name='history_model',
            name='poll_name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_poll_core.poll_model'),
        ),
        migrations.AddField(
            model_name='answer_model',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_poll_core.question_model'),
        ),
    ]
