# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-27 08:48
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_poll_core', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pollanswer',
            old_name='question_id',
            new_name='question',
        ),
        migrations.RenameField(
            model_name='pollhistory',
            old_name='answer_id',
            new_name='answer',
        ),
        migrations.RenameField(
            model_name='pollhistory',
            old_name='question_id',
            new_name='question',
        ),
    ]
