# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-21 14:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_poll_core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='history_model',
            name='user',
            field=models.CharField(max_length=100),
        ),
    ]
