# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-27 08:48
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_poll_core', '0002_auto_20160227_1418'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pollanswer',
            name='question',
        ),
        migrations.RemoveField(
            model_name='pollhistory',
            name='answer',
        ),
        migrations.RemoveField(
            model_name='pollhistory',
            name='question',
        ),
        migrations.RemoveField(
            model_name='pollhistory',
            name='user_id',
        ),
        migrations.DeleteModel(
            name='PollAnswer',
        ),
        migrations.DeleteModel(
            name='PollHistory',
        ),
        migrations.DeleteModel(
            name='PollQuestion',
        ),
    ]
