# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-03-01 12:47
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_poll_core', '0005_auto_20160227_1420'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pollanswer',
            name='question_id',
        ),
        migrations.RemoveField(
            model_name='pollhistory',
            name='answer_id',
        ),
        migrations.RemoveField(
            model_name='pollhistory',
            name='question_id',
        ),
        migrations.RemoveField(
            model_name='pollhistory',
            name='user_id',
        ),
        migrations.DeleteModel(
            name='PollAnswer',
        ),
        migrations.DeleteModel(
            name='PollHistory',
        ),
        migrations.DeleteModel(
            name='PollQuestion',
        ),
    ]
